import { Geist, Geist_Mono, Nunito } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

const nexaRound = localFont({
  src: [
    {
      path: "../public/fonts/nexaround-trial-thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/nexaround-trial-light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/nexaround-trial-book.otf",
      weight: "350",
      style: "normal",
    },
    {
      path: "../public/fonts/nexaround-trial-regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/nexaround-trial-bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/nexaround-trial-extrabold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/nexaround-trial-heavy.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/nexaround-trial-ultra.otf",
      weight: "950",
      style: "normal",
    },
    {
      path: "../public/fonts/nexaround-trial-glow.otf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-nexa-round",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} ${nexaRound.variable}`}>
        {children}
      </body>
    </html>
  );
}
